# Generated by Django 6.0.1 on 2026-02-24 08:12

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена (р.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание ')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ')),
                ('deliveryDate', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('receiveCode', models.CharField(default=catalog.models.generate_receive_code, max_length=20, verbose_name='Код')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('delivered', 'Завершен')], default='new', max_length=20, verbose_name='Статус ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('pickupPoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pickuppoint', verbose_name='Пункт выдачи')),
                ('products', models.ManyToManyField(to='catalog.product', verbose_name='Товары в заказе')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('unauthorized', 'Неавторизирован'), ('authorized', 'Авторизирован'), ('editor', 'Редактор'), ('admin', 'Админ')], default='authorized', max_length=20, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
